# Generated by Django 5.0.7 on 2024-07-18 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='stock',
            new_name='estoque',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='preco',
        ),
    ]
