# Generated by Django 5.0.7 on 2024-07-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shirt',
            old_name='pro_category',
            new_name='shi_category',
        ),
    ]
