# Generated by Django 5.0.7 on 2024-07-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_stock_products_estoque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='nome',
            new_name='name_p',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='preco',
            new_name='price_p',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='estoque',
            new_name='stock_p',
        ),
    ]
